//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backfofficegestiondebibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID_Log { get; set; }
        public Nullable<System.DateTime> DateHeure { get; set; }
        public string Action { get; set; }
        public Nullable<int> ID_Personne { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
