//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backfofficegestiondebibliotheque
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliothequeDBEntities1 : DbContext
    {
        public BibliothequeDBEntities1()
            : base("name=BibliothequeDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emprunt> Emprunts { get; set; }
        public virtual DbSet<Livre> Livres { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
    }
}
